apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  labels:
    app: fe-law-ai
    env: staging
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: fe-law-ai
      env: staging
  template:
    metadata:
      labels:
        app: fe-law-ai
        env: staging
    spec:
      containers:
      - name: fe-law-ai-container
        image: kunalmane/fe-law-ai-project:v1.2
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
