apiVersion: v1
kind: Service
metadata:
  name: fe-law-ai-service
  labels:
    app: fe-law-ai
    env: staging
spec:
  type: ClusterIP
  selector:
    app: fe-law-ai
    env: staging
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
