apiVersion: v1
kind: Service
metadata:
  name: fe-law-ai-node-port-service
  labels:
    app: fe-law-ai
    env: staging
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
  selector:
    app: fe-law-ai
    env: staging